name: CI

on:
  push:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  postgres:
    strategy:
      fail-fast: false
      matrix:
        db:
          - name: PostgreSQL
            url: "postgres://postgres:postgres@localhost:5432/postgres"
          - name: MySQL
            url: "mysql://test:test@localhost:3306/test"

    runs-on: ubuntu-latest
    name: Test with ${{ matrix.db.name }}
    env:
      DATABASE_URL: ${{ matrix.db.url }}
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
      - run: pip install -r requirements.txt

      - name: Change config
        run: ./scripts/change-config.sh

      - name: Upgrade to django-constance v3
        run: ./scripts/upgrade-constance.sh

      - name: Check persisted
        run: ./scripts/check-config-persisted.sh
